# OGBench Cube (single).
env_id: swm/OGBCube-v0
dataset: ogbench/cube_single_expert.lance
cell: cub10
callables:
  - {method: set_state, args: {qpos: {value: qpos}, qvel: {value: qvel}}}
  - method: set_target_pos
    args:
      cube_id: {value: 0, in_dataset: false}
      target_pos: {value: goal_privileged_block_0_pos}
      target_quat: {value: goal_privileged_block_0_quat}
history_keys: [pixels, observation]
process_keys: [action, observation]
state_col: privileged_block_0_pos
world_kwargs: {env_type: single, ob_type: states, multiview: false, width: 224, height: 224, visualize_info: false, terminate_at_goal: true}
